baseURL: https://adrian.ooo

languageCode: en-us
title: "Adrian McFarlane"
theme: "toha"
languages:
  en:
    languageName: English
    weight: 1


markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: https://github.com/confy/adrian.ooo
  enableBlogPost: true
  enableTOC: true
  newsletter:
    enable: false